const supabase = require('../lib/supabase');

/**
 * Creates a new Codeband Run in Supabase
 */
async function createRun(prompt) {
    const { data, error } = await supabase
        .from('runs')
        .insert([{ prompt, status: 'PENDING', shared_context: {} }])
        .select()
        .single();

    if (error) throw new Error(`Failed to create run: ${error.message}`);
    return data;
}

/**
 * Updates the status of a run (e.g. to 'PLAN_LOCKED', 'ESCALATED', etc.)
 */
async function updateRunStatus(runId, status) {
    const { error } = await supabase
        .from('runs')
        .update({ status })
        .eq('id', runId);

    if (error) throw new Error(`Failed to update run status: ${error.message}`);
}

/**
 * Updates the shared Band state (JSON context)
 */
async function updateSharedContext(runId, newContext) {
    const { error } = await supabase
        .from('runs')
        .update({ shared_context: newContext })
        .eq('id', runId);

    if (error) throw new Error(`Failed to update shared context: ${error.message}`);
}

/**
 * Fetches the current shared state for a run
 */
async function getSharedContext(runId) {
    const { data, error } = await supabase
        .from('runs')
        .select('shared_context')
        .eq('id', runId)
        .single();

    if (error) throw new Error(`Failed to fetch shared context: ${error.message}`);
    return data.shared_context;
}

/**
 * Logs an event generated by one of the swarm agents
 */
async function logAgentEvent(runId, agentName, eventType, output) {
    const { error } = await supabase
        .from('agent_events')
        .insert([{ run_id: runId, agent_name: agentName, event_type: eventType, output }]);

    if (error) throw new Error(`Failed to log agent event: ${error.message}`);
}

module.exports = {
    createRun,
    updateRunStatus,
    updateSharedContext,
    getSharedContext,
    logAgentEvent
};
