const { z } = require('zod');
const { PromptTemplate } = require('@langchain/core/prompts');
const { getLLM, formatBlueprint } = require('../lib/llm');
const bandState = require('../services/bandState');

// Helper to sanitize JSON response from LLM
function sanitizeJSON(content) {
    let clean = content.trim();
    const matches = clean.match(/```json\s*([\s\S]*?)\s*```/);
    if (matches && matches[1]) {
        clean = matches[1].trim();
    } else {
        clean = clean.replace(/```json/gi, '').replace(/```/g, '').trim();
    }
    return JSON.parse(clean);
}

/**
 * Catalyst (LangChain QA Reviewer)
 * Evaluates the generated HTML from Kuli for syntax errors and requirement matching.
 */
async function execute(runId) {
    const currentContext = await bandState.getSharedContext(runId);
    const htmlCode = currentContext?.html;
    const blueprint = currentContext?.blueprint;
    const assignedModel = currentContext?.routing?.catalyst_model || 'qwen3.6-flash';

    if (!htmlCode) {
        throw new Error("Catalyst cannot review: No HTML code found in context.");
    }

    await bandState.logAgentEvent(runId, 'Catalyst', 'INFO', { 
        message: `Performing code syntax and requirement QA with model ${assignedModel}...` 
    });
    
    const promptTemplate = new PromptTemplate({
        template: `You are Catalyst, the Senior QA Code Reviewer.
Your job is to review the following HTML/Tailwind/Vanilla JS code generated by Kuli.
You must perform a meticulous QA pass to ensure:
1. **Valid HTML/CSS/JS**: Ensure there are no JavaScript runtime errors, unclosed tags, or duplicate id attributes.
2. **Framework Alignment**: The code uses Tailwind CSS correctly without syntax typos.
3. **Blueprint Compliance**: Ensure all components and modules specified in the blueprint are fully implemented.
4. **No Placeholders**: There should be no "TODO", "Lorem Ipsum", or generic comments where functionality was expected.
5. **Interactive Quality**: The Vanilla JS logic actually connects elements correctly and handles clicks, inputs, or animations smoothly.

Code to review:
\`\`\`html
{code}
\`\`\`

Blueprint Constraints:
{blueprint}

Output strictly a JSON object with two keys:
{{
  "passed": true/false (boolean),
  "feedback": "string detailing what needs to be fixed, or LGTM if passed"
}}
Do not output schema definitions. Output raw JSON or standard markdown code fences.
`,
        inputVariables: ["code", "blueprint"]
    });

    const modelsToTry = [assignedModel, 'qwen3.6-flash', 'gemini-3.1-flash-lite-preview', 'qwen3.6-plus'];
    let lastError = null;
    let response = null;

    for (const model of modelsToTry) {
        try {
            console.log(`[Catalyst] Invoking LangChain LLM with model: ${model}`);
            const llm = getLLM(model);
            const chain = promptTemplate.pipe(llm);
            response = await chain.invoke({ 
                code: htmlCode,
                blueprint: formatBlueprint(blueprint)
            });
            break;
        } catch (err) {
            console.warn(`[Catalyst Model ${model}] failed: ${err.message}`);
            lastError = err;
        }
    }

    if (!response) {
        const errorMsg = `Catalyst failed all fallback models. Last error: ${lastError ? lastError.message : 'Unknown'}`;
        await bandState.logAgentEvent(runId, 'Catalyst', 'ERROR', { error: errorMsg });
        throw new Error(errorMsg);
    }

    const content = response.content || String(response);
    console.log('[Catalyst] Raw review response:', content);

    try {
        const reviewData = sanitizeJSON(content);

        // Validate shape
        if (typeof reviewData.passed !== 'boolean' || typeof reviewData.feedback !== 'string') {
            throw new Error('Catalyst returned an invalid review JSON shape.');
        }

        // Update Band State with the review results
        await bandState.updateSharedContext(runId, { ...currentContext, review: reviewData });
        
        if (reviewData.passed) {
            await bandState.logAgentEvent(runId, 'Catalyst', 'QA_PASSED', { 
                message: `Code checks out perfectly! Syntax, interactive logic, and responsive bindings look solid. LGTM.` 
            });
        } else {
            await bandState.logAgentEvent(runId, 'Catalyst', 'QA_FAILED', { 
                message: `QA issues found: ${reviewData.feedback}. Kuli, please correct these.` 
            });
        }

        return reviewData;

    } catch (error) {
        console.error("Catalyst QA parsing error:", error);
        // Fallback to pass to prevent pipeline lock
        const fallbackReview = { passed: true, feedback: 'LGTM' };
        await bandState.updateSharedContext(runId, { ...currentContext, review: fallbackReview });
        return fallbackReview;
    }
}

module.exports = { execute };

