const { z } = require('zod');
const { StructuredOutputParser } = require('@langchain/core/output_parsers');
const { PromptTemplate } = require('@langchain/core/prompts');
const { getLLM, formatBlueprint } = require('../lib/llm');
const bandState = require('../services/bandState');

/**
 * Catalyst (LangChain QA Reviewer)
 * Evaluates the generated HTML from Kuli for syntax errors and requirement matching.
 */
async function execute(runId) {
    const currentContext = await bandState.getSharedContext(runId);
    const htmlCode = currentContext?.html;
    const blueprint = currentContext?.blueprint;

    if (!htmlCode) {
        throw new Error("Catalyst cannot review: No HTML code found in context.");
    }

    await bandState.logAgentEvent(runId, 'Catalyst', 'INFO', { message: `I'm on it! Let me review Kuli's code to make sure it matches the blueprint without any syntax errors...` });
    
    // We use a strong model for review, e.g., gpt-4o
    const llm = getLLM('gpt-4o');

    const promptTemplate = new PromptTemplate({
        template: `You are Catalyst, the Senior QA Code Reviewer.
Your job is to review the following HTML/Tailwind/Vanilla JS code generated by Kuli.
Ensure that:
1. It is perfectly valid HTML.
2. It includes the required components from the Blueprint.
3. It respects the aesthetic principles (glassmorphism, tailwind utility classes).

Code to review:
\`\`\`html
{code}
\`\`\`

Blueprint Constraints:
{blueprint}

Output strictly a JSON object with two keys:
{{
  "passed": true/false (boolean),
  "feedback": "string detailing what needs to be fixed, or LGTM if passed"
}}
Do not output schema definitions. Output raw JSON or standard markdown code fences.
`,
        inputVariables: ["code", "blueprint"]
    });

    try {
        const chain = promptTemplate.pipe(llm);
        
        let response;
        const maxRetries = 5;
        for (let attempt = 1; attempt <= maxRetries; attempt++) {
            try {
                response = await chain.invoke({ 
                    code: htmlCode,
                    blueprint: formatBlueprint(blueprint)
                });
                break;
            } catch (err) {
                console.warn(`[Catalyst Attempt ${attempt}] failed: ${err.message}`);
                if (attempt === maxRetries) throw err;
                await new Promise(res => setTimeout(res, 5000 * attempt));
            }
        }

        const content = response.content || String(response);
        console.log('[Catalyst] Raw review response:', content);

        let reviewData;
        try {
            reviewData = JSON.parse(content);
        } catch (e) {
            let clean = content;
            const matches = content.match(/```json\s*([\s\S]*?)\s*```/g);
            if (matches && matches.length > 0) {
                const lastMatch = matches[matches.length - 1];
                clean = lastMatch.replace(/```json/gi, '').replace(/```/g, '').trim();
            } else {
                clean = content.replace(/```json/gi, '').replace(/```/g, '').trim();
            }
            reviewData = JSON.parse(clean);
        }

        // Validate shape
        if (typeof reviewData.passed !== 'boolean' || typeof reviewData.feedback !== 'string') {
            throw new Error('Catalyst returned an invalid review JSON shape.');
        }

        // Update Band State with the review results
        await bandState.updateSharedContext(runId, { ...currentContext, review: reviewData });
        
        if (reviewData.passed) {
            await bandState.logAgentEvent(runId, 'Catalyst', 'QA_PASSED', { message: `Code looks solid. Nice work, Kuli! LGTM.` });
        } else {
            await bandState.logAgentEvent(runId, 'Catalyst', 'QA_FAILED', { message: `Found a few issues, Kuli. Please fix this: ${reviewData.feedback}` });
        }

        return reviewData;

    } catch (error) {
        console.error("Catalyst QA Error:", error);
        await bandState.logAgentEvent(runId, 'Catalyst', 'ERROR', { error: error.message });
        throw error;
    }
}

module.exports = { execute };
