const { z } = require('zod');
const { StructuredOutputParser } = require('@langchain/core/output_parsers');
const { PromptTemplate } = require('@langchain/core/prompts');
const { getLLM } = require('../lib/llm');
const bandState = require('../services/bandState');

/**
 * Catalyst (LangChain QA Reviewer)
 * Evaluates the generated HTML from Kuli for syntax errors and requirement matching.
 */
async function execute(runId) {
    const currentContext = await bandState.getSharedContext(runId);
    const htmlCode = currentContext?.html;
    const blueprint = currentContext?.blueprint;

    if (!htmlCode) {
        throw new Error("Catalyst cannot review: No HTML code found in context.");
    }

    await bandState.logAgentEvent(runId, 'Catalyst', 'INFO', { message: 'Analyzing Kuli\'s generated code for errors and constraints...' });
    
    // We use a strong model for review, e.g., gpt-4o
    const llm = getLLM('gpt-4o');

    const schema = z.object({
        passed: z.boolean().describe("True if the code has no errors and follows the blueprint. False if fixes are required."),
        feedback: z.string().describe("Detailed feedback on what needs to be fixed. If passed is true, this can be empty or 'LGTM'.")
    });

    const parser = StructuredOutputParser.fromZodSchema(schema);
    const formatInstructions = parser.getFormatInstructions();

    const promptTemplate = new PromptTemplate({
        template: `You are Catalyst, the Senior QA Code Reviewer.
Your job is to review the following HTML/Tailwind/Vanilla JS code generated by Kuli.
Ensure that:
1. It is perfectly valid HTML.
2. It includes the required components from the Blueprint.
3. It respects the aesthetic principles (glassmorphism, tailwind utility classes).

Code to review:
\`\`\`html
{code}
\`\`\`

Blueprint Constraints:
{blueprint}

{format_instructions}
`,
        inputVariables: ["code", "blueprint"],
        partialVariables: { format_instructions: formatInstructions }
    });

    try {
        const chain = promptTemplate.pipe(llm).pipe(parser);
        
        const reviewData = await chain.invoke({ 
            code: htmlCode,
            blueprint: JSON.stringify(blueprint)
        });

        // Update Band State with the review results
        await bandState.updateSharedContext(runId, { ...currentContext, review: reviewData });
        
        if (reviewData.passed) {
            await bandState.logAgentEvent(runId, 'Catalyst', 'QA_PASSED', { message: 'Code passed QA review.' });
        } else {
            await bandState.logAgentEvent(runId, 'Catalyst', 'QA_FAILED', { feedback: reviewData.feedback });
        }

        return reviewData;

    } catch (error) {
        console.error("Catalyst QA Error:", error);
        await bandState.logAgentEvent(runId, 'Catalyst', 'ERROR', { error: error.message });
        throw error;
    }
}

module.exports = { execute };
