import sys
import autogen
import warnings

# Suppress warnings to keep stdout clean for Node.js
warnings.filterwarnings('ignore')

def main():
    if len(sys.argv) < 6:
        print("Usage: python kuli_agent.py <prompt> <blueprint_json> <modelName> <apiKey> <baseUrl>", file=sys.stderr)
        sys.exit(1)
        
    prompt = sys.argv[1]
    blueprint_json = sys.argv[2]
    model_name = sys.argv[3]
    api_key = sys.argv[4]
    base_url = sys.argv[5]
    
    llm_config = {
        "config_list": [
            {
                "model": model_name,
                "api_key": api_key,
                "base_url": base_url,
            }
        ],
        "temperature": 0.2
    }
    
    assistant = autogen.AssistantAgent(
        name="Kuli",
        llm_config=llm_config,
        system_message="""You are Kuli, the Master Frontend Coder.
Your job is to generate a single index.html file containing HTML, Tailwind CSS (via CDN), and Vanilla JS based on the provided blueprint.
Return ONLY valid HTML code. Do NOT wrap the code in markdown formatting (like ```html). Provide absolutely no explanations, just the raw code.
"""
    )
    
    user_proxy = autogen.UserProxyAgent(
        name="User",
        human_input_mode="NEVER",
        max_consecutive_auto_reply=0,
        code_execution_config=False
    )
    
    # Check if there is a 6th argument for feedback
    feedback = sys.argv[6] if len(sys.argv) > 6 else None

    if feedback and feedback != "None":
        message = f"User Prompt: {prompt}\n\nArchitectural Blueprint:\n{blueprint_json}\n\nQA Review Feedback:\n{feedback}\n\nPlease generate the corrected raw HTML code fixing the issues mentioned in the QA feedback."
    else:
        message = f"User Prompt: {prompt}\n\nArchitectural Blueprint:\n{blueprint_json}\n\nPlease generate the complete raw HTML code."
    
    # We trap stdout during initiate_chat to prevent autogen's internal logging from polluting our stdout payload
    import io
    from contextlib import redirect_stdout
    
    trap = io.StringIO()
    with redirect_stdout(trap):
        user_proxy.initiate_chat(
            assistant,
            message=message,
            summary_method="last_msg"
        )
    
    # Extract the last message generated by Kuli
    last_message = user_proxy.last_message()["content"]
    
    # Print the pure HTML payload to real stdout for Node.js to capture
    print(last_message)

if __name__ == "__main__":
    main()
